// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251211204320_ToplamBedel")]
    partial class ToplamBedel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Ortak.Deger", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("KategoriId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Deger", "Ortak");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Adi = "Yol",
                            KategoriId = 1L,
                            Kodu = "YOL",
                            Silindi = false,
                            SiraNo = 1
                        },
                        new
                        {
                            Id = 2L,
                            Adi = "Asfalt",
                            KategoriId = 1L,
                            Kodu = "ASF",
                            Silindi = false,
                            SiraNo = 2
                        },
                        new
                        {
                            Id = 3L,
                            Adi = "Bina",
                            KategoriId = 1L,
                            Kodu = "BNA",
                            Silindi = false,
                            SiraNo = 3
                        },
                        new
                        {
                            Id = 4L,
                            Adi = "Tamamlandı",
                            KategoriId = 2L,
                            Kodu = "TMMD",
                            Silindi = false,
                            SiraNo = 1
                        },
                        new
                        {
                            Id = 5L,
                            Adi = "Devam Ediyor",
                            KategoriId = 2L,
                            Kodu = "DEV",
                            Silindi = false,
                            SiraNo = 2
                        },
                        new
                        {
                            Id = 6L,
                            Adi = "Açık İhale",
                            KategoriId = 3L,
                            Kodu = "ACK",
                            Silindi = false,
                            SiraNo = 1
                        },
                        new
                        {
                            Id = 7L,
                            Adi = "DMO",
                            KategoriId = 3L,
                            Kodu = "DMO",
                            Silindi = false,
                            SiraNo = 2
                        },
                        new
                        {
                            Id = 8L,
                            Adi = "Vatandaş",
                            KategoriId = 4L,
                            Kodu = "VTN",
                            Silindi = false,
                            SiraNo = 1
                        },
                        new
                        {
                            Id = 9L,
                            Adi = "Personel",
                            KategoriId = 4L,
                            Kodu = "PRS",
                            Silindi = false,
                            SiraNo = 2
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ortak.Ilce", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Ilce", "Ortak");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Adi = "Akyurt",
                            Silindi = false
                        },
                        new
                        {
                            Id = 2L,
                            Adi = "Altındağ",
                            Silindi = false
                        },
                        new
                        {
                            Id = 3L,
                            Adi = "Ayaş",
                            Silindi = false
                        },
                        new
                        {
                            Id = 4L,
                            Adi = "Bala",
                            Silindi = false
                        },
                        new
                        {
                            Id = 5L,
                            Adi = "Beypazarı",
                            Silindi = false
                        },
                        new
                        {
                            Id = 6L,
                            Adi = "Çamlıdere",
                            Silindi = false
                        },
                        new
                        {
                            Id = 7L,
                            Adi = "Çankaya",
                            Silindi = false
                        },
                        new
                        {
                            Id = 8L,
                            Adi = "Çubuk",
                            Silindi = false
                        },
                        new
                        {
                            Id = 9L,
                            Adi = "Elmadağ",
                            Silindi = false
                        },
                        new
                        {
                            Id = 10L,
                            Adi = "Etimesgut",
                            Silindi = false
                        },
                        new
                        {
                            Id = 11L,
                            Adi = "Evren",
                            Silindi = false
                        },
                        new
                        {
                            Id = 12L,
                            Adi = "Gölbaşı",
                            Silindi = false
                        },
                        new
                        {
                            Id = 13L,
                            Adi = "Güdül",
                            Silindi = false
                        },
                        new
                        {
                            Id = 14L,
                            Adi = "Haymana",
                            Silindi = false
                        },
                        new
                        {
                            Id = 15L,
                            Adi = "Kahramankazan",
                            Silindi = false
                        },
                        new
                        {
                            Id = 16L,
                            Adi = "Kalecik",
                            Silindi = false
                        },
                        new
                        {
                            Id = 17L,
                            Adi = "Keçiören",
                            Silindi = false
                        },
                        new
                        {
                            Id = 18L,
                            Adi = "Kızılcahamam",
                            Silindi = false
                        },
                        new
                        {
                            Id = 19L,
                            Adi = "Mamak",
                            Silindi = false
                        },
                        new
                        {
                            Id = 20L,
                            Adi = "Nallıhan",
                            Silindi = false
                        },
                        new
                        {
                            Id = 21L,
                            Adi = "Polatlı",
                            Silindi = false
                        },
                        new
                        {
                            Id = 22L,
                            Adi = "Pursaklar",
                            Silindi = false
                        },
                        new
                        {
                            Id = 23L,
                            Adi = "Sincan",
                            Silindi = false
                        },
                        new
                        {
                            Id = 24L,
                            Adi = "Şereflikoçhisar",
                            Silindi = false
                        },
                        new
                        {
                            Id = 25L,
                            Adi = "Yenimahalle",
                            Silindi = false
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ortak.Kategori", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Kategori", "Ortak");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Adi = "Proje Tipi",
                            Silindi = false
                        },
                        new
                        {
                            Id = 2L,
                            Adi = "Proje Durumu",
                            Silindi = false
                        },
                        new
                        {
                            Id = 3L,
                            Adi = "İhale Türü",
                            Silindi = false
                        },
                        new
                        {
                            Id = 4L,
                            Adi = "Hedef Kitlesi",
                            Silindi = false
                        });
                });

            modelBuilder.Entity("Domain.Entities.ProjeModul.Proje", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Bedeli")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullanici")
                        .HasColumnType("bigint");

                    b.Property<long>("HedefKitleId")
                        .HasColumnType("bigint");

                    b.Property<long>("IhaleTuruId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("IlaveSozlesmeBedeli")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("OlusturanKullanici")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaZamani")
                        .HasColumnType("datetime2");

                    b.Property<long>("ProjeDurumuId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProjeTipiId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<decimal>("ToplamBedel")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HedefKitleId");

                    b.HasIndex("IhaleTuruId");

                    b.HasIndex("ProjeDurumuId");

                    b.HasIndex("ProjeTipiId");

                    b.ToTable("Proje", "Proje");
                });

            modelBuilder.Entity("Domain.Entities.ProjeModul.ProjeIlceDagilimi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("IlceId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("IlceyeOdenenBedeli")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ProjeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IlceId");

                    b.HasIndex("ProjeId");

                    b.ToTable("ProjeIlceDagilimi", "Proje");
                });

            modelBuilder.Entity("Domain.Entities.Ortak.Deger", b =>
                {
                    b.HasOne("Domain.Entities.Ortak.Kategori", "Kategori")
                        .WithMany("Degerler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("Domain.Entities.ProjeModul.Proje", b =>
                {
                    b.HasOne("Domain.Entities.Ortak.Deger", "HedefKitle")
                        .WithMany("ProjelerAsHedefKitle")
                        .HasForeignKey("HedefKitleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Ortak.Deger", "IhaleTuru")
                        .WithMany("ProjelerAsIhaleTuru")
                        .HasForeignKey("IhaleTuruId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Ortak.Deger", "ProjeDurumu")
                        .WithMany("ProjelerAsProjeDurumu")
                        .HasForeignKey("ProjeDurumuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Ortak.Deger", "ProjeTipi")
                        .WithMany("ProjelerAsProjeTipi")
                        .HasForeignKey("ProjeTipiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HedefKitle");

                    b.Navigation("IhaleTuru");

                    b.Navigation("ProjeDurumu");

                    b.Navigation("ProjeTipi");
                });

            modelBuilder.Entity("Domain.Entities.ProjeModul.ProjeIlceDagilimi", b =>
                {
                    b.HasOne("Domain.Entities.Ortak.Ilce", "Ilce")
                        .WithMany("IlceDagilimlari")
                        .HasForeignKey("IlceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ProjeModul.Proje", "Proje")
                        .WithMany("IlceDagilimlari")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilce");

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("Domain.Entities.Ortak.Deger", b =>
                {
                    b.Navigation("ProjelerAsHedefKitle");

                    b.Navigation("ProjelerAsIhaleTuru");

                    b.Navigation("ProjelerAsProjeDurumu");

                    b.Navigation("ProjelerAsProjeTipi");
                });

            modelBuilder.Entity("Domain.Entities.Ortak.Ilce", b =>
                {
                    b.Navigation("IlceDagilimlari");
                });

            modelBuilder.Entity("Domain.Entities.Ortak.Kategori", b =>
                {
                    b.Navigation("Degerler");
                });

            modelBuilder.Entity("Domain.Entities.ProjeModul.Proje", b =>
                {
                    b.Navigation("IlceDagilimlari");
                });
#pragma warning restore 612, 618
        }
    }
}
