// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251208210510_Kategori-Deger-Insert-Seed")]
    partial class KategoriDegerInsertSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Ortak.Deger", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("KategoriId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Deger", "Ortak");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Adi = "Yol",
                            KategoriId = 1L,
                            Kodu = "YOL",
                            Silindi = false,
                            SiraNo = 1
                        },
                        new
                        {
                            Id = 2L,
                            Adi = "Asfalt",
                            KategoriId = 1L,
                            Kodu = "ASF",
                            Silindi = false,
                            SiraNo = 2
                        },
                        new
                        {
                            Id = 3L,
                            Adi = "Bina",
                            KategoriId = 1L,
                            Kodu = "BNA",
                            Silindi = false,
                            SiraNo = 3
                        },
                        new
                        {
                            Id = 4L,
                            Adi = "Tamamlandı",
                            KategoriId = 2L,
                            Kodu = "TMMD",
                            Silindi = false,
                            SiraNo = 1
                        },
                        new
                        {
                            Id = 5L,
                            Adi = "Devam Ediyor",
                            KategoriId = 2L,
                            Kodu = "DEV",
                            Silindi = false,
                            SiraNo = 2
                        },
                        new
                        {
                            Id = 6L,
                            Adi = "Açık İhale",
                            KategoriId = 3L,
                            Kodu = "ACK",
                            Silindi = false,
                            SiraNo = 1
                        },
                        new
                        {
                            Id = 7L,
                            Adi = "DMO",
                            KategoriId = 3L,
                            Kodu = "DMO",
                            Silindi = false,
                            SiraNo = 2
                        },
                        new
                        {
                            Id = 8L,
                            Adi = "Vatandaş",
                            KategoriId = 4L,
                            Kodu = "VTN",
                            Silindi = false,
                            SiraNo = 1
                        },
                        new
                        {
                            Id = 9L,
                            Adi = "Personel",
                            KategoriId = 4L,
                            Kodu = "PRS",
                            Silindi = false,
                            SiraNo = 2
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ortak.Kategori", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Kategori", "Ortak");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Adi = "Proje Tipi",
                            Silindi = false
                        },
                        new
                        {
                            Id = 2L,
                            Adi = "Proje Durumu",
                            Silindi = false
                        },
                        new
                        {
                            Id = 3L,
                            Adi = "İhale Türü",
                            Silindi = false
                        },
                        new
                        {
                            Id = 4L,
                            Adi = "Hedef Kitlesi",
                            Silindi = false
                        });
                });

            modelBuilder.Entity("Domain.Entities.Proje.Proje", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Bedeli")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullanici")
                        .HasColumnType("bigint");

                    b.Property<string>("HedefKitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IhaleTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IlaveSozlesmeBedeli")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("OlusturanKullanici")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaZamani")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Projeler");
                });

            modelBuilder.Entity("Domain.Entities.Ortak.Deger", b =>
                {
                    b.HasOne("Domain.Entities.Ortak.Kategori", "Kategori")
                        .WithMany("Degerler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("Domain.Entities.Ortak.Kategori", b =>
                {
                    b.Navigation("Degerler");
                });
#pragma warning restore 612, 618
        }
    }
}
