// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316074944_AddAuditLog")]
    partial class AddAuditLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Kullanici.AppRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Kullanici.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Log.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Ortak.Deger", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("KategoriId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("KategoriId", "Adi")
                        .IsUnique();

                    b.ToTable("Deger", "Ortak");
                });

            modelBuilder.Entity("Domain.Entities.Ortak.Ilce", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Ilce", "Ortak");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Adi = "Akyurt",
                            Silindi = false
                        },
                        new
                        {
                            Id = 2L,
                            Adi = "Altındağ",
                            Silindi = false
                        },
                        new
                        {
                            Id = 3L,
                            Adi = "Ayaş",
                            Silindi = false
                        },
                        new
                        {
                            Id = 4L,
                            Adi = "Bala",
                            Silindi = false
                        },
                        new
                        {
                            Id = 5L,
                            Adi = "Beypazarı",
                            Silindi = false
                        },
                        new
                        {
                            Id = 6L,
                            Adi = "Çamlıdere",
                            Silindi = false
                        },
                        new
                        {
                            Id = 7L,
                            Adi = "Çankaya",
                            Silindi = false
                        },
                        new
                        {
                            Id = 8L,
                            Adi = "Çubuk",
                            Silindi = false
                        },
                        new
                        {
                            Id = 9L,
                            Adi = "Elmadağ",
                            Silindi = false
                        },
                        new
                        {
                            Id = 10L,
                            Adi = "Etimesgut",
                            Silindi = false
                        },
                        new
                        {
                            Id = 11L,
                            Adi = "Evren",
                            Silindi = false
                        },
                        new
                        {
                            Id = 12L,
                            Adi = "Gölbaşı",
                            Silindi = false
                        },
                        new
                        {
                            Id = 13L,
                            Adi = "Güdül",
                            Silindi = false
                        },
                        new
                        {
                            Id = 14L,
                            Adi = "Haymana",
                            Silindi = false
                        },
                        new
                        {
                            Id = 15L,
                            Adi = "Kahramankazan",
                            Silindi = false
                        },
                        new
                        {
                            Id = 16L,
                            Adi = "Kalecik",
                            Silindi = false
                        },
                        new
                        {
                            Id = 17L,
                            Adi = "Keçiören",
                            Silindi = false
                        },
                        new
                        {
                            Id = 18L,
                            Adi = "Kızılcahamam",
                            Silindi = false
                        },
                        new
                        {
                            Id = 19L,
                            Adi = "Mamak",
                            Silindi = false
                        },
                        new
                        {
                            Id = 20L,
                            Adi = "Nallıhan",
                            Silindi = false
                        },
                        new
                        {
                            Id = 21L,
                            Adi = "Polatlı",
                            Silindi = false
                        },
                        new
                        {
                            Id = 22L,
                            Adi = "Pursaklar",
                            Silindi = false
                        },
                        new
                        {
                            Id = 23L,
                            Adi = "Sincan",
                            Silindi = false
                        },
                        new
                        {
                            Id = 24L,
                            Adi = "Şereflikoçhisar",
                            Silindi = false
                        },
                        new
                        {
                            Id = 25L,
                            Adi = "Yenimahalle",
                            Silindi = false
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ortak.Kategori", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<bool>("ProjedeGoster")
                        .HasColumnType("bit");

                    b.Property<bool>("ProjedeZorunlu")
                        .HasColumnType("bit");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Kategori", "Ortak");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Adi = "Proje Tipi",
                            Aktif = false,
                            ProjedeGoster = false,
                            ProjedeZorunlu = false,
                            Silindi = false
                        },
                        new
                        {
                            Id = 2L,
                            Adi = "Proje Durumu",
                            Aktif = false,
                            ProjedeGoster = false,
                            ProjedeZorunlu = false,
                            Silindi = false
                        },
                        new
                        {
                            Id = 3L,
                            Adi = "İhale Türü",
                            Aktif = false,
                            ProjedeGoster = false,
                            ProjedeZorunlu = false,
                            Silindi = false
                        },
                        new
                        {
                            Id = 4L,
                            Adi = "Hedef Kitlesi",
                            Aktif = false,
                            ProjedeGoster = false,
                            ProjedeZorunlu = false,
                            Silindi = false
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ortak.ProjeKategoriDeger", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DegerId")
                        .HasColumnType("bigint");

                    b.Property<long>("KategoriId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProjeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DegerId");

                    b.HasIndex("KategoriId");

                    b.HasIndex("ProjeId");

                    b.ToTable("ProjeKategoriDeger", "Proje");
                });

            modelBuilder.Entity("Domain.Entities.ProjeModul.Proje", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Bedeli")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullanici")
                        .HasColumnType("bigint");

                    b.Property<decimal>("IlaveSozlesmeBedeli")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("OlusturanKullanici")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaZamani")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<decimal>("ToplamBedel")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Proje", "Proje");
                });

            modelBuilder.Entity("Domain.Entities.ProjeModul.ProjeIlceDagilimi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("IlceId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("IlceyeOdenenBedeli")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ProjeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IlceId");

                    b.HasIndex("ProjeId");

                    b.ToTable("ProjeIlceDagilimi", "Proje");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Ortak.Deger", b =>
                {
                    b.HasOne("Domain.Entities.Ortak.Kategori", "Kategori")
                        .WithMany("Degerler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("Domain.Entities.Ortak.ProjeKategoriDeger", b =>
                {
                    b.HasOne("Domain.Entities.Ortak.Deger", "Deger")
                        .WithMany()
                        .HasForeignKey("DegerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Ortak.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ProjeModul.Proje", "Proje")
                        .WithMany("KategoriDegerleri")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deger");

                    b.Navigation("Kategori");

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("Domain.Entities.ProjeModul.ProjeIlceDagilimi", b =>
                {
                    b.HasOne("Domain.Entities.Ortak.Ilce", "Ilce")
                        .WithMany("IlceDagilimlari")
                        .HasForeignKey("IlceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ProjeModul.Proje", "Proje")
                        .WithMany("IlceDagilimlari")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilce");

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Domain.Entities.Kullanici.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("Domain.Entities.Kullanici.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("Domain.Entities.Kullanici.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Domain.Entities.Kullanici.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Kullanici.AppUser", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("Domain.Entities.Kullanici.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Kullanici.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Domain.Entities.Ortak.Ilce", b =>
                {
                    b.Navigation("IlceDagilimlari");
                });

            modelBuilder.Entity("Domain.Entities.Ortak.Kategori", b =>
                {
                    b.Navigation("Degerler");
                });

            modelBuilder.Entity("Domain.Entities.ProjeModul.Proje", b =>
                {
                    b.Navigation("IlceDagilimlari");

                    b.Navigation("KategoriDegerleri");
                });
#pragma warning restore 612, 618
        }
    }
}
